#### Importando Bibliotecas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

#### Entrada dos dados

In [2]:
df_andando = pd.read_csv("./arduino-science-jorunal/Andando.csv")
df_caminhando = pd.read_csv("./arduino-science-jorunal/Caminhando.csv")
df_correndo = pd.read_csv("./arduino-science-jorunal/Correndo.csv")

In [3]:
df_andando.head()

,timestamp,AmbientLightSensor,DecibelSource,PitchSensor,AccX,AccY,AccZ
0,1763074334936,1.0,NaN,NaN,-0.07605,2.08500,9.391951
1,1763074334953,NaN,48.155316,162.535924,NaN,NaN,NaN
2,1763074334958,NaN,NaN,85.885417,NaN,NaN,NaN
3,1763074334993,NaN,47.077705,85.885417,NaN,NaN,NaN
4,1763074335005,NaN,NaN,NaN,0.37305,2.07795,9.399000

In [4]:
df_caminhando.head()

,timestamp,AmbientLightSensor,DecibelSource,PitchSensor,AccX,AccY,AccZ
0,1763074862430,11.0,NaN,NaN,-0.15705,NaN,NaN
1,1763074862441,12.0,NaN,NaN,NaN,NaN,NaN
2,1763074862443,NaN,NaN,NaN,NaN,5.322,NaN
3,1763074862444,NaN,NaN,NaN,NaN,NaN,8.632951
4,1763074862447,NaN,NaN,NaN,-1.15095,NaN,NaN

In [5]:
df_correndo.head()

,timestamp,AmbientLightSensor,DecibelSource,PitchSensor,AccX,AccY,AccZ
0,1763141947708,NaN,NaN,NaN,2.622,-7.249050,6.73200
1,1763141947725,NaN,NaN,NaN,1.875,-9.009001,1.40205
2,1763141947727,NaN,67.496179,73.620199,NaN,NaN,NaN
3,1763141947744,NaN,NaN,NaN,0.330,-11.049001,NaN
4,1763141947745,NaN,NaN,NaN,NaN,NaN,-0.78795

#### Tamanho dos datasets

In [6]:
print(f"Número de instâncias(Andando): {len(df_andando['timestamp'])}")
print(f"Número de instâncias(Caminhando): {len(df_caminhando['timestamp'])}")
print(f"Número de instâncias(Correndo): {len(df_correndo['timestamp'])}")

Número de instâncias(Andando): 9660
Número de instâncias(Caminhando): 4833
Número de instâncias(Correndo): 3714

#### Verificar potenciais tratamentos de dados

In [7]:
df_andando.dtypes

timestamp               int64
AmbientLightSensor    float64
DecibelSource         float64
PitchSensor           float64
AccX                  float64
AccY                  float64
AccZ                  float64
dtype: object

In [8]:
df_caminhando.dtypes

timestamp               int64
AmbientLightSensor    float64
DecibelSource         float64
PitchSensor           float64
AccX                  float64
AccY                  float64
AccZ                  float64
dtype: object

In [9]:
df_correndo.dtypes

timestamp               int64
AmbientLightSensor    float64
DecibelSource         float64
PitchSensor           float64
AccX                  float64
AccY                  float64
AccZ                  float64
dtype: object

#### Filtrando as features

In [10]:
df_filtrar_andando = df_andando[['timestamp', 'AccX', 'AccY', 'AccZ']]
df_filtrar_caminhando = df_caminhando[['timestamp', 'AccX', 'AccY', 'AccZ']]
df_filtrar_correndo = df_correndo[['timestamp', 'AccX', 'AccY', 'AccZ']]

In [11]:
df_filtrar_andando.head

<bound method NDFrame.head of           timestamp     AccX     AccY      AccZ
0     1763074334936 -0.07605  2.08500  9.391951
1     1763074334953      NaN      NaN       NaN
2     1763074334958      NaN      NaN       NaN
3     1763074334993      NaN      NaN       NaN
4     1763074335005  0.37305  2.07795  9.399000
...             ...      ...      ...       ...
9655  1763074424393      NaN      NaN       NaN
9656  1763074424404  0.47400  4.35705  8.496000
9657  1763074424405      NaN      NaN       NaN
9658  1763074424426      NaN  4.36200       NaN
9659  1763074424427  0.46005      NaN  8.491051

[9660 rows x 4 columns]>

#### Filtrando as Instâncias

In [12]:
df_filtrar_andando_integra = df_filtrar_andando.dropna()
df_filtrar_caminhando_integra = df_filtrar_caminhando.dropna()
df_filtrar_correndo_integra = df_filtrar_correndo.dropna()

In [13]:
len(df_filtrar_andando_integra)

3046

In [14]:

df_filtrar_andando_integra.head()

       timestamp     AccX     AccY      AccZ
0  1763074334936 -0.07605  2.08500  9.391951
4  1763074335005  0.37305  2.07795  9.399000
5  1763074335021  2.26995  1.29705  9.388950
7  1763074335040  2.24805  0.94500  9.382051
9  1763074335059  1.75995  0.62895  8.950951

In [15]:
len(df_filtrar_caminhando_integra)

843

In [16]:

df_filtrar_caminhando_integra.head()

        timestamp     AccX     AccY       AccZ
7   1763074862463 -1.14795  4.02705   8.635051
8   1763074862487 -1.14105  2.94195   8.641951
10  1763074862503 -1.50795  2.96400   9.777000
17  1763074862562 -0.93300  3.82605  10.246051
19  1763074862589 -0.39405  3.83505   9.777000

In [17]:
len(df_filtrar_correndo_integra)

731

In [18]:
df_filtrar_correndo_integra.head()

        timestamp       AccX       AccY     AccZ
0   1763141947708   2.622000  -7.249050  6.73200
1   1763141947725   1.875000  -9.009001  1.40205
6   1763141947763  -0.652950 -14.439001 -2.77005
8   1763141947782   3.009000 -17.995050 -4.31505
18  1763141947860  28.518002  -5.590050 -4.31505